### PR TITLE
i am fucking

### PR DESCRIPTION
**Pull request by zTags**
fucking

### CODE REVIEW

**Review by itsmebombie — CHANGES_REQUESTED** [review]
lmao

**Review by itsmebombie — CHANGES_REQUESTED** [review]
deez

**Review by itsmebombie — CHANGES_REQUESTED** [review]
i am stipid

**Comment by itsmebombie** [comment]
becase i am stupid and forgot to mention that every file must have a function called "astolfo" that prints every string you give it and you must call it with the string "Hello, sertdfyguhi!" lmao

**Review by itsmebombie — APPROVED** [review]

**Review by itsmebombie — CHANGES_REQUESTED** [review]
h

**Comment by zTags** [comment]
oh

**Comment by zTags** [comment]
stop spamming my gh notifs tu

**Comment by itsmebombie** [comment]
whoops

**Review by itsmebombie — APPROVED** [review]
deez nuts

**Comment by zTags** [comment]
pog

**Review by itsmebombie — APPROVED** [review]

**Comment by itsmebombie** [comment]
fuck yeah finally

**Comment by zTags** [comment]
eyyyy

**Pull request merged**
